jQuery(document).ready(function(){"use strict";if(jQuery.magnificPopup)
{jQuery('.w-gallery-tnails-h').magnificPopup({type:'image',delegate:'a',gallery:{enabled:!0,navigateByImgClick:!0,preload:[0,1]},removalDelay:300,mainClass:'mfp-fade'});jQuery('a[ref=magnificPopup][class!=direct-link]').magnificPopup({type:'image'})}
if(jQuery().carousello){jQuery(".w-listing.type_carousel, .w-clients.type_carousel, .w-portfolio.type_carousel").carousello()}
if(jQuery().isotope){var portfolioContainer=jQuery('.w-portfolio.type_sortable .w-portfolio-list-h');if(portfolioContainer){portfolioContainer.imagesLoaded(function(){portfolioContainer.isotope({itemSelector:'.w-portfolio-item',layoutMode:'fitRows'})});jQuery('.w-filters-item').each(function(){var item=jQuery(this),link=item.find('.w-filters-item-link');link.click(function(){if(!item.hasClass('active')){jQuery('.w-filters-item').removeClass('active');item.addClass('active');var selector=jQuery(this).attr('data-filter');portfolioContainer.isotope({filter:selector});return!1}})});jQuery('.w-portfolio-item-meta-tags a').each(function(){jQuery(this).click(function(){var selector=jQuery(this).attr('data-filter'),topFilterLink=jQuery('a[class="w-filters-item-link"][data-filter="'+selector+'"]'),topFilter=topFilterLink.parent('.w-filters-item');if(!topFilter.hasClass('active')){jQuery('.w-filters-item').removeClass('active');topFilter.addClass('active');portfolioContainer.isotope({filter:selector});return!1}})})}
var postsContainer=jQuery('.w-blog.type_masonry .w-blog-list');if(postsContainer.length){postsContainer.imagesLoaded(function(){postsContainer.isotope({itemSelector:'.w-blog-entry',layoutMode:'masonry'})});var postsResizeTimer;jQuery(window).resize(function(){window.clearTimeout(postsResizeTimer);postsResizeTimer=window.setTimeout(function(){postsContainer.isotope('reLayout')},50)})}
var galleryContainer=jQuery('.w-gallery.type_masonry .w-gallery-tnails-h');if(galleryContainer.length){galleryContainer.imagesLoaded(function(){galleryContainer.isotope({layoutMode:'masonry'})});var galleryResizeTimer;jQuery(window).resize(function(){window.clearTimeout(galleryResizeTimer);galleryResizeTimer=window.setTimeout(function(){galleryContainer.isotope('reLayout')},50)})}}
if(jQuery().revolution){if(jQuery.fn.cssOriginal!==undefined){jQuery.fn.css=jQuery.fn.cssOriginal}
jQuery('.fullwidthbanner').revolution({delay:9000,startwidth:1000,startheight:500,soloArrowLeftHOffset:20,soloArrowLeftVOffset:0,soloArrowRightHOffset:20,soloArrowRightVOffset:0,onHoverStop:"on",fullWidth:"on",hideThumbs:!1,shadow:0})}
jQuery('iframe').each(function(){var url=jQuery(this).attr("src");var char="?";if(jQuery.inArray("?",url)!==-1){char="&"}
jQuery(this).attr("src",url+char+"wmode=transparent")});if(jQuery().waypoint){jQuery('body').imagesLoaded(function(){jQuery('.animate_afc, .animate_afl, .animate_afr, .animate_aft, .animate_afb, .animate_wfc, .animate_hfc, .animate_rfc, .animate_rfl, .animate_rfr').waypoint(function(){if(!jQuery(this).hasClass('animate_start')){var elm=jQuery(this);setTimeout(function(){elm.addClass('animate_start')},20)}},{offset:'85%',triggerOnce:!0})})}
var scrollHandlerPageTO=!1,scrollHandlerPage=function(){var scrollPosition=parseInt(jQuery(window).scrollTop(),10),windowHeight=jQuery(window).height()-0,windowWidth=jQuery(window).width()-0;if(scrollPosition>=windowHeight){jQuery('.w-toplink').addClass('active')}else{jQuery('.w-toplink').removeClass('active')}
if(jQuery('.l-canvas').hasClass('headerpos_fixed')){var topHeaderHeight,middleHeaderHeight;if(scrollPosition>0&&windowWidth>1023){if(!jQuery('.l-header').hasClass('state_sticky')){jQuery('.l-header').addClass('state_sticky')}
if(jQuery('.l-canvas').hasClass('headertype_extended')){if(scrollPosition>40){topHeaderHeight=Math.max(76-scrollPosition,0);jQuery('.l-subheader.at_top').css({'height':topHeaderHeight+'px','overflow':'hidden'})}else{jQuery('.l-subheader.at_top').css({'height':'','overflow':''})}}
middleHeaderHeight=Math.max(Math.round(90-scrollPosition),60);jQuery('.l-subheader.at_middle').css({'height':middleHeaderHeight+'px','line-height':middleHeaderHeight+'px'});jQuery('.w-logo').css({'width':40+'px'})}else{if(jQuery('.l-header').hasClass('state_sticky')){jQuery('.l-header').removeClass('state_sticky')}
jQuery('.l-subheader.at_middle').css({'height':'','line-height':''});jQuery('.l-subheader.at_top').css({'height':'','overflow':''});jQuery('.w-logo').css({'width':'auto'})}}},menuHandler=function(){jQuery('.l-header .w-nav').each(function(){var nav=jQuery(this),navControl=nav.find('.w-nav-control'),navList=nav.find('.w-nav-list.level_1'),navSubLists=navList.find('.w-nav-item.with_sublevel .w-nav-list'),windowWidth=jQuery(window).width()-0,navRunning=!1,subNavRunning=!1;if(windowWidth<1000){var listHeight,listOpen=!1,navSubControls=navList.find('.w-nav-item.with_sublevel .w-nav-hint');if(!nav.hasClass('touch_enabled')){nav.addClass('touch_enabled');navList.css({display:'none'});navSubLists.css({display:'none'})}
navControl.off('click').click(function(){if(!navRunning){navRunning=!0;if(listOpen){navList.slideUp(250,function(){navRunning=!1});listOpen=!1}else{navList.slideDown(250,function(){navRunning=!1});listOpen=!0}}});navSubControls.off('click').click(function(){if(!navRunning){navRunning=!0;var subList=jQuery(this).closest('.w-nav-item-h').find('.w-nav-list').first(),subListOpen=subList.data('subListOpen'),subListHeight=subList.data('subListHeight');if(subListOpen){subList.slideUp(250,function(){navRunning=!1});subListOpen=!1}else{subList.slideDown(250,function(){navRunning=!1});subListOpen=!0}
subList.data('subListOpen',subListOpen);subList.data('subListHeight',subListHeight)}
return!1})}else{nav.removeClass('touch_enabled');navList.css({height:'',display:''});navSubLists.css({height:'',display:''});navControl.off('click')}})};scrollHandlerPage();menuHandler();jQuery(window).scroll(function(){scrollHandlerPage()});jQuery(window).resize(function(){if(scrollHandlerPageTO!==!1){window.clearTimeout(scrollHandlerPageTO)}
scrollHandlerPageTO=window.setTimeout(function(){scrollHandlerPage();menuHandler()},5)});jQuery('.w-toplink').click(function(event){event.preventDefault();event.stopPropagation();jQuery.smoothScroll({scrollTarget:'#'})})});(function($){var version='1.4.10',defaults={exclude:[],excludeWithin:[],offset:0,direction:'top',scrollElement:null,scrollTarget:null,beforeScroll:function(){},afterScroll:function(){},easing:'swing',speed:400,autoCoefficent:2},getScrollable=function(opts){var scrollable=[],scrolled=!1,dir=opts.dir&&opts.dir=='left'?'scrollLeft':'scrollTop';this.each(function(){if(this==document||this==window){return}
var el=$(this);if(el[dir]()>0){scrollable.push(this)}else{el[dir](1);scrolled=el[dir]()>0;if(scrolled){scrollable.push(this)}
el[dir](0)}});if(!scrollable.length){this.each(function(index){if(this.nodeName==='BODY'){scrollable=[this]}})}
if(opts.el==='first'&&scrollable.length>1){scrollable=[scrollable[0]]}
return scrollable},isTouch='ontouchend' in document;$.fn.extend({scrollable:function(dir){var scrl=getScrollable.call(this,{dir:dir});return this.pushStack(scrl)},firstScrollable:function(dir){var scrl=getScrollable.call(this,{el:'first',dir:dir});return this.pushStack(scrl)},smoothScroll:function(options){options=options||{};var opts=$.extend({},$.fn.smoothScroll.defaults,options),locationPath=$.smoothScroll.filterPath(location.pathname);this.unbind('click.smoothscroll').bind('click.smoothscroll',function(event){var link=this,$link=$(this),exclude=opts.exclude,excludeWithin=opts.excludeWithin,elCounter=0,ewlCounter=0,include=!0,clickOpts={},hostMatch=((location.hostname===link.hostname)||!link.hostname),pathMatch=opts.scrollTarget||($.smoothScroll.filterPath(link.pathname)||locationPath)===locationPath,thisHash=escapeSelector(link.hash);if(!opts.scrollTarget&&(!hostMatch||!pathMatch||!thisHash)){include=!1}else{while(include&&elCounter<exclude.length){if($link.is(escapeSelector(exclude[elCounter++]))){include=!1}}
while(include&&ewlCounter<excludeWithin.length){if($link.closest(excludeWithin[ewlCounter++]).length){include=!1}}}
if(include){event.preventDefault();$.extend(clickOpts,opts,{scrollTarget:opts.scrollTarget||thisHash,link:link});$.smoothScroll(clickOpts)}});return this}});$.smoothScroll=function(options,px){var opts,$scroller,scrollTargetOffset,speed,scrollerOffset=0,offPos='offset',scrollDir='scrollTop',aniProps={},aniOpts={},scrollprops=[];if(typeof options==='number'){opts=$.fn.smoothScroll.defaults;scrollTargetOffset=options}else{opts=$.extend({},$.fn.smoothScroll.defaults,options||{});if(opts.scrollElement){offPos='position';if(opts.scrollElement.css('position')=='static'){opts.scrollElement.css('position','relative')}}}
opts=$.extend({link:null},opts);scrollDir=opts.direction=='left'?'scrollLeft':scrollDir;if(opts.scrollElement){$scroller=opts.scrollElement;scrollerOffset=$scroller[scrollDir]()}else{$scroller=$('html, body').firstScrollable()}
opts.beforeScroll.call($scroller,opts);scrollTargetOffset=(typeof options==='number')?options:px||($(opts.scrollTarget)[offPos]()&&$(opts.scrollTarget)[offPos]()[opts.direction])||0;aniProps[scrollDir]=scrollTargetOffset+scrollerOffset+opts.offset;speed=opts.speed;if(speed==='auto'){speed=aniProps[scrollDir]||$scroller.scrollTop();speed=speed/opts.autoCoefficent}
aniOpts={duration:speed,easing:opts.easing,complete:function(){opts.afterScroll.call(opts.link,opts)}};if(opts.step){aniOpts.step=opts.step}
if($scroller.length){$scroller.stop().animate(aniProps,aniOpts)}else{opts.afterScroll.call(opts.link,opts)}};$.smoothScroll.version=version;$.smoothScroll.filterPath=function(string){return string.replace(/^\//,'').replace(/(index|default).[a-zA-Z]{3,4}$/,'').replace(/\/$/,'')};$.fn.smoothScroll.defaults=defaults;function escapeSelector(str){return str.replace(/(:|\.)/g,'\\$1')}})(jQuery)